# Copyright Â© 2021 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# Note: Any changes to this workflow would be used only after merging into develop
name: Build e2e tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop]
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  build:
    runs-on: k8s-runner-e2e

    # We allow builds:
    # 1) When triggered manually
    # 2) When it's a merge into a branch
    # 3) For PRs that are labeled as build and
    #  - It's a code change
    #  - A build label was just added
    # A bit complex, but prevents builds when other labels are manipulated
    if: >
      github.event_name == 'workflow_dispatch'
      || github.event_name == 'push'
      || (contains(github.event.pull_request.labels.*.name, 'build')
         && (github.event.action != 'labeled' || github.event.label.name == 'build')
         )

    steps:
      # Pinned 1.0.0 version
      - uses: actions/checkout@v2.3.4
        with:
          path: plugin
      - name: Checkout e2e test repo
        uses: actions/checkout@v2.3.4
        with:
          repository: cdapio/cdap-e2e-tests
          path: e2e
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ github.workflow }}
      - name: Run tests
        run: python3 e2e/src/main/scripts/run_e2e_test.py
      - name: Upload report
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: Cucumber report
          path: ./plugin/target/cucumber-reports
      - name: Upload debug files
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: Debug files
          path: ./**/target/e2e-debug
      - name: Upload files to GCS
        uses: google-github-actions/upload-cloud-storage@v0
        if: always()
        with:
          path: ./plugin/target/cucumber-reports
          destination: e2e-tests-cucumber-reports/${{ github.event.repository.name }}/${{ github.ref }}
      - name: github-status-action
        uses: Sibz/github-status-action@67af1f4042a5a790681aad83c44008ca6cfab83d
        if: always()
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
          context: Cucumber report
          sha: ${{github.event.pull_request.head.sha || github.sha}}
